name: $(Date:yyyMMdd)$(Rev:.r)
stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      name: Hosted Windows 2019 with VS2019
    variables:
      BuildConfiguration: Debug
      BuildPlatform: any cpu

    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'
    
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
    
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '$(Parameters.TestProjects)'
        arguments: '--configuration $(BuildConfiguration)'
    
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True
    
    - task: VSBuild@1
      displayName: 'Build solution Database/Database.sln'
      inputs:
        solution: Database/Database.sln
    
    - task: CopyFiles@2
      displayName: 'Copy dacpac, IaC, and data Files to Staging'
      inputs:
        Contents: |
         Database/bin/**/*.dacpac
         IaC/**
         data/**
        TargetFolder: '$(Build.StagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()

- stage: DeployToDev
  jobs:
  - deployment: DeployInfraWebDB
    displayName: Deploy Infra Web and DB
    pool:
      name: Hosted Windows 2019 with VS2019
      variables:
        servicePrincipal: http://AbelDeployPrincipal
        servicePrincipalTenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
        azureSubscriptionName: ca-abewan-demo-test
        resourceGroupName: abellearndbrg3
        location: southcentralus
        adminlogin: abel
        servername: abellearndbserverdev
        startip: 0.0.0.0
        endip: 0.0.0.0
        dbName: learndb
        dbEdition: GeneralPurpose
        dbFamily: Gen4
        dbCapacity: 1
        dbZoneRedundant: false
        webAppName: abellearndbwebappdev
        webAppSku: B1
        webStorageAccountName: abellearnwebstoragedev
        webStorageAccountRegion: southcentralus
        webStorageAccountSku: Standard_LRS
        storageContainerName: abellearnstoragedev
        dbComputeModel: Serverless
    environment: 'courses-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
            patterns: '**/*'

          - task: PowerShell@2
            displayName : 'Provision DB and Web'
            inputs:
              filePath: '$(Pipeline.Workspace)/drop/IaC/provisionWebDB.ps1'
              arguments: '-servicePrincipal $(servicePrincipal) -servicePrincipalSecret $(servicePrincipalSecret) -servicePrincipalTenantId $(servicePrincipalTenantId) -azureSubscriptionName $(azureSubscriptionName) -resourceGroupName $(resourceGroupName) -location $(location) -adminlogin $(adminlogindev) -adminPassword $(adminPasswordDev) -servername $(servernamedev) -startip $(startip) -endip $(endip) -dbName $(dbName) -dbEdition $(dbEdition) -dbFamily $(dbFamily) -dbCapacity $(dbCapacity) -dbZoneRedundant $(dbZoneRedundant) -webAppName $(webAppNameDev) -webAppSku $(webAppSku) -releaseDirectory $(Agent.ReleaseDirectory) -webStorageAccountName $(webStorageAccountNameDev) -webStorageAccountRegion $(webStorageAccountRegion) -webStorageAccountSku $(webStorageAccountSku) -storageContainerName $(storageContainerNameDev) -dbComputeModel $(dbComputeModel)'
          
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'ca-abewan-demo-test (e97f6c4e-c830-479b-81ad-1aff1dd07470)'
              appType: 'webApp'
              WebAppName: '$(webAppName)'
              packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

- stage: DeployToProd
  jobs:
  - deployment: DeployInfraWebDB
    displayName: Deploy Infra Web and DB
    pool:
      name: Hosted Windows 2019 with VS2019
      variables:
        servicePrincipal: http://AbelDeployPrincipal
        servicePrincipalTenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
        azureSubscriptionName: ca-abewan-demo-test
        resourceGroupName: abellearndbrg3
        location: southcentralus
        adminlogin: abel
        servername: abellearndbserverprod
        startip: 0.0.0.0
        endip: 0.0.0.0
        dbName: learndb
        dbEdition: GeneralPurpose
        dbFamily: Gen4
        dbCapacity: 1
        dbZoneRedundant: false
        webAppName: abellearndbwebappprod
        webAppSku: B1
        webStorageAccountName: abellearnwebstorageprod
        webStorageAccountRegion: southcentralus
        webStorageAccountSku: Standard_LRS
        storageContainerName: abellearnstorageprod
        dbComputeModel: Serverless
    environment: 'courses-prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
            patterns: '**/*'

          - task: PowerShell@2
            displayName : 'Provision DB and Web'
            inputs:
              filePath: '$(Pipeline.Workspace)/drop/IaC/provisionWebDB.ps1'
              arguments: '-servicePrincipal $(servicePrincipal) -servicePrincipalSecret $(servicePrincipalSecret) -servicePrincipalTenantId $(servicePrincipalTenantId) -azureSubscriptionName $(azureSubscriptionName) -resourceGroupName $(resourceGroupName) -location $(location) -adminlogin $(adminloginprod) -adminPassword $(adminPasswordProd) -servername $(servernameprod) -startip $(startip) -endip $(endip) -dbName $(dbName) -dbEdition $(dbEdition) -dbFamily $(dbFamily) -dbCapacity $(dbCapacity) -dbZoneRedundant $(dbZoneRedundant) -webAppName $(webAppNameProd -webAppSku $(webAppSku) -releaseDirectory $(Agent.ReleaseDirectory) -webStorageAccountName $(webStorageAccountNameProd) -webStorageAccountRegion $(webStorageAccountRegion) -webStorageAccountSku $(webStorageAccountSku) -storageContainerName $(storageContainerNameProd) -dbComputeModel $(dbComputeModel)'
          
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'ca-abewan-demo-test (e97f6c4e-c830-479b-81ad-1aff1dd07470)'
              appType: 'webApp'
              WebAppName: '$(webAppName)'
              packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'